# Generated by Django 4.1.7 on 2023-03-16 01:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('codigo', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('nombre', models.CharField(max_length=100)),
                ('presupuesto', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('codigo', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('nit', models.CharField(max_length=9)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido1', models.CharField(max_length=100)),
                ('apellido2', models.CharField(max_length=100)),
                ('codigo_departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empleado.departamento')),
            ],
        ),
    ]
