# Generated by Django 4.1.7 on 2023-03-16 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0005_alter_departamento_codigo_alter_empleado_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='nit',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
